-- This migration is intentionally a no-op.
--
-- The table rename from form_fields/form_responses/form_response_values to
-- data_controls/records/record_values happens in the next migration:
-- 20260630130000_data_controls_records.
--
-- Keeping this migration as a no-op preserves migration history and avoids
-- failing on fresh databases where data_controls does not exist yet.
