BEGIN;

CREATE TYPE "FIELDTYPE_new" AS ENUM ('TEXT', 'CHECKBOX', 'RADIO', 'DROPDOWN', 'DATE');

ALTER TABLE "form_fields"
ALTER COLUMN "type" TYPE "FIELDTYPE_new"
USING ("type"::text::"FIELDTYPE_new");

ALTER TYPE "FIELDTYPE" RENAME TO "FIELDTYPE_old";
ALTER TYPE "FIELDTYPE_new" RENAME TO "FIELDTYPE";
DROP TYPE "FIELDTYPE_old";

COMMIT;
